name: CI
on: [push]
jobs:
  build-node:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    env:
      CI: "true"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["10.x", "12.x", "14.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }} # tests across multiple Node versions

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
  build-deno:
    name: Build, lint, and test on deno ${{ matrix.deno }} and ${{ matrix.os }}
    env:
      CI: "true"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno: ["1.6.2"]
        os: [ubuntu-latest]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
      - name: Test
        run: deno test ./deno_test
